# https://github.com/marketplace/actions/easy-zip-files

name: üóÇÔ∏è Zip file for ModLoaders
on: workflow_dispatch
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: vimtor/action-zip@v1.1
      with:
        files: localization/fr.lua localization/Better_FR.lua
        dest: BetterFR.zip
    - uses: actions/upload-artifact@v4
      with:
        name: BetterFR
        path: ${{ github.workspace }}/BetterFR.zip